version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: YourStrongPassw0rd
      ACCPEPT_EULA: Y
    ports:
      - "1401:1433"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"